apiVersion: v1
kind: Service
metadata:
  labels:
    app: cache-svc
  name: cache-svc-0
spec:
  clusterIP: None
  ports:
  - name: "memcached" 
    port: 11211
  - name: "count"
    port: 11212
  - name: "content"
    port: 11213
  - name: "services"
    port: 11214
  - name: "packager"
    port: 11215
  - name: "httpsclient"
    port: 11216
  selector:
    interface: cache-svc-0
status: {}
