apiVersion: v1
kind: Service
metadata:
  labels:
    app: log-svc
  name: log-svc-0
spec:
  clusterIP: None
  ports:
  - name: "logport"
    port: 24224
  - name: "dimdataport"
    port: 24220
  - name: "metricsport"
    port: 24221
  - name: "containerlogsport"
    port: 24222
  selector:
    interface: log-svc-0
status: {}
