apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-svc
  name: mysql-svc-0
spec:
  clusterIP: None
  ports:
  - name: "mysql"
    port: 3306
  - name: "mysql-grp-repl"
    port: 33061  
  selector:
    interface: mysql-svc-0
status: {}
