apiVersion: v1
kind: Service
metadata:
  name: reporting-app-0
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: reporting-set-0-0
  #loadBalancerIP: ""
  ports:
  - name: "grafana-http-port"
    port: 3000
    protocol: TCP
    targetPort: 3000
status:
  loadBalancer: {}